mysql:
  namespace: mysql

  image:
    repository: mysql
    tag: 8.0
  replicas: 2
  port: 3306

  service:
    clusterIP: None

  secrets:
    MYSQL_ROOT_PASSWORD: "1234"
    MYSQL_USER: "app_user"
    MYSQL_PASSWORD: "1234"

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  storage:
    size: "2Gi"

  tolerations:
      key: "app"
      operator: "Equal"
      value: "mysql"
      effect: "NoSchedule"

  affinity:
    key: "app"
    operator: In
    values: "mysql"
    topologyKey: "kubernetes.io/hostname"
    nodeAffinity:
      key: "app"
      operator: In
      values: "mysql"
