apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nodeport
  namespace: {{ .Values.todoapp.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.todoapp.service.port }}
    targetPort: {{ .Values.todoapp.service.targetPort }}
    nodePort: {{ .Values.todoapp.service.nodePort }}
